import type { OnboardingQuestion } from '../types.js';

export const tier0Questions: OnboardingQuestion[] = [
  {
    id: 'Q1_motions',
    tier: 0,
    title: 'Revenue Motions',
    config_targets: ['pipelines', 'revenue_motions', 'named_filters'],
    requires_data: ['deals'],
    requires_questions: [],
    trigger: null,
    hypothesis_generator: 'generateMotionsHypothesis',
    prompt_intro: "I scanned your CRM. Here's how I'd segment your revenue motions based on your pipeline structure and deal size distributions:",
    input_hint: "Tell me what looks right or what you'd change. How many distinct selling motions do you have, and how would you define them?",
    can_skip: true,
    skip_message: "No problem — I'll treat all deals as one motion. You can refine this in Settings anytime.",
    skip_default: { pipelines: [{ name: 'All Deals', filters: [] }] },
    show_artifact: true,
  },
  {
    id: 'Q2_calendar',
    tier: 0,
    title: 'Fiscal Calendar & Targets',
    config_targets: ['cadence.fiscal_year_start_month', 'cadence.quota_period', 'goals'],
    requires_data: ['deals'],
    requires_questions: [],
    trigger: null,
    hypothesis_generator: 'generateCalendarHypothesis',
    prompt_intro: "Your deals cluster around certain dates. Here's what I'm inferring about your fiscal calendar:",
    input_hint: "Is this right? What are your targets for this quarter — total, and by motion if you have them?",
    can_skip: true,
    skip_message: "Got it — I'll use calendar quarters starting January. Brief will show pipeline totals without attainment tracking.",
    skip_default: { cadence: { fiscal_year_start_month: 1, quota_period: 'quarterly' } },
    show_artifact: true,
  },
  {
    id: 'Q3_stages',
    tier: 0,
    title: 'Stage Classification',
    config_targets: ['stage_configs', 'win_rate'],
    requires_data: ['deals'],
    requires_questions: [],
    trigger: null,
    hypothesis_generator: 'generateStagesHypothesis',
    prompt_intro: "Here's what I see for your deal stages. I've classified them based on patterns — confirm anything that looks off:",
    input_hint: "Anything miscategorized? Any parking lot stages (deals that get parked but aren't truly active)? Any retired stages I should ignore?",
    can_skip: true,
    skip_message: "No problem — I'll use the stage settings from your CRM sync. Unknown stages will count as active pipeline.",
    skip_default: { stage_configs: [] },
    show_artifact: true,
  },
  {
    id: 'Q4_team',
    tier: 0,
    title: 'Team Roster',
    config_targets: ['teams.roles', 'teams.excluded_owners'],
    requires_data: ['deals'],
    requires_questions: [],
    trigger: null,
    hypothesis_generator: 'generateTeamHypothesis',
    prompt_intro: "I found deal owners in your CRM. Here's how I'd classify them as reps vs non-reps:",
    input_hint: "Who's missing or miscategorized? Any new hires I should know about? Who are the managers?",
    can_skip: true,
    skip_message: "Got it — I'll treat all deal owners as reps. You can exclude accounts or mark managers in Settings.",
    skip_default: { teams: { excluded_owners: [] } },
    show_artifact: true,
  },
  {
    id: 'Q10_delivery',
    tier: 0,
    title: 'Delivery Preferences',
    config_targets: ['cadence.timezone', 'delivery'],
    requires_data: [],
    requires_questions: ['Q1_motions'],
    trigger: null,
    hypothesis_generator: 'generateDeliveryHypothesis',
    prompt_intro: "A few quick questions about how you want to receive updates:",
    input_hint: "What timezone are you in? Do you have a Monday pipeline review? Which Slack channel should updates go to?",
    can_skip: true,
    skip_message: "No problem — briefs will generate at 7 AM UTC. You can configure Slack delivery in Settings.",
    skip_default: { cadence: { timezone: 'UTC' } },
    show_artifact: false,
  },
];
