import type { OnboardingQuestion } from '../types.js';

export const tier23Questions: OnboardingQuestion[] = [
  {
    id: 'Q11_methodology',
    tier: 2,
    title: 'Sales Methodology',
    config_targets: ['definitions.methodology', 'definitions.qualified_definition'],
    requires_data: ['deals'],
    requires_questions: ['Q3_stages'],
    trigger: 'after:pipeline-hygiene',
    hypothesis_generator: 'generateMethodologyHypothesis',
    prompt_intro: "I just ran your first pipeline health check. I'm using generic qualification criteria — do you use a formal methodology?",
    input_hint: "MEDDIC/MEDDPICC, BANT, SPICED, or custom? Or should I just use stage + contact count?",
    can_skip: true,
    skip_message: "Got it — I'll flag deals missing amount, close date, and a contact.",
    skip_default: { definitions: { methodology: 'generic' } },
    show_artifact: false,
  },
  {
    id: 'Q12_activity',
    tier: 2,
    title: 'Activity Expectations',
    config_targets: ['activities.engagement_weights'],
    requires_data: ['activities'],
    requires_questions: ['Q4_team'],
    trigger: 'after:rep-scorecard',
    hypothesis_generator: 'generateActivityHypothesis',
    prompt_intro: "Your reps have varying activity levels. Here's the distribution:",
    input_hint: "What does 'good' look like per week for your team? For enterprise reps? Mid-market?",
    can_skip: true,
    skip_message: "Got it — I'll compare reps against the team average rather than a fixed benchmark.",
    skip_default: { activities: { benchmark_mode: 'relative' } },
    show_artifact: false,
  },
  {
    id: 'Q15_competitors',
    tier: 2,
    title: 'Competitors',
    config_targets: ['definitions.competitors'],
    requires_data: [],
    requires_questions: [],
    trigger: 'after:competitive-intelligence',
    hypothesis_generator: 'generateCompetitorsHypothesis',
    prompt_intro: "Based on what I found, here are your likely competitors:",
    input_hint: "Is this right? Anyone else I should watch for in call transcripts and deal notes?",
    can_skip: true,
    skip_message: "Got it — I'll watch for competitor mentions without a specific watchlist.",
    skip_default: { definitions: { competitors: [] } },
    show_artifact: false,
  },
  {
    id: 'Q17_buying_committee',
    tier: 2,
    title: 'Buying Committee',
    config_targets: ['thresholds.minimum_contacts_per_deal'],
    requires_data: ['deals'],
    requires_questions: ['Q4_team'],
    trigger: 'after:single-thread-alert',
    hypothesis_generator: 'generateBuyingCommitteeHypothesis',
    prompt_intro: "Based on your won deals, here's how buying committees are structured:",
    input_hint: "Want me to flag deals missing exec involvement? What roles are critical for your motion?",
    can_skip: true,
    skip_message: "Got it — I'll flag deals with fewer than 2 contacts as single-threaded.",
    skip_default: { thresholds: { minimum_contacts_per_deal: 2 } },
    show_artifact: false,
  },
  {
    id: 'Q25_loss_reasons',
    tier: 3,
    title: 'Loss Reason Categories',
    config_targets: ['definitions.loss_reasons'],
    requires_data: ['deals'],
    requires_questions: [],
    trigger: 'after:win-loss-analysis',
    hypothesis_generator: 'generateLossReasonsHypothesis',
    prompt_intro: "Your closed-lost deals have many different reason values. Here's my suggested grouping:",
    input_hint: "Do these categories make sense? Want to rename or consolidate any?",
    can_skip: true,
    skip_message: "Got it — I'll use the raw loss reason values without grouping.",
    skip_default: { definitions: { loss_reasons: [] } },
    show_artifact: false,
  },
];
