import type { OnboardingQuestion } from '../types.js';

export const tier1Questions: OnboardingQuestion[] = [
  {
    id: 'Q5_stale',
    tier: 1,
    title: 'Stale Deal Thresholds',
    config_targets: ['thresholds.stale_deal_days'],
    requires_data: ['deals'],
    requires_questions: ['Q1_motions'],
    trigger: null,
    hypothesis_generator: 'generateStaleHypothesis',
    prompt_intro: "Based on your deal velocity, here's what 'stale' looks like for each motion:",
    input_hint: "Do these thresholds feel right? Too aggressive, too lenient? Are there stages where long durations are normal?",
    can_skip: true,
    skip_message: "Got it — I'll use a 14-day warning and 30-day critical threshold across all motions.",
    skip_default: { thresholds: { stale_deal_days: 14, critical_deal_days: 30 } },
    show_artifact: false,
  },
  {
    id: 'Q6_forecast',
    tier: 1,
    title: 'Forecast Method',
    config_targets: ['forecast_method', 'forecast_category_field'],
    requires_data: ['deals'],
    requires_questions: [],
    trigger: null,
    hypothesis_generator: 'generateForecastHypothesis',
    prompt_intro: "Here's what I can tell about how your team categorizes deals for forecasting:",
    input_hint: "Do your reps use forecast categories (Commit, Best Case, Pipeline)? Which field? Or should I calculate probability from stage?",
    can_skip: true,
    skip_message: "Got it — I'll use stage-based weighted pipeline probability. No forecast category required from reps.",
    skip_default: { forecast_method: 'stage_probability' },
    show_artifact: false,
  },
  {
    id: 'Q7_winrate',
    tier: 1,
    title: 'Win Rate Calculation',
    config_targets: ['win_rate.minimum_stage', 'win_rate.lookback_days'],
    requires_data: ['deals'],
    requires_questions: ['Q3_stages'],
    trigger: null,
    hypothesis_generator: 'generateWinRateHypothesis',
    prompt_intro: "Here's your win rate breakdown — I found something worth asking about:",
    input_hint: "Which win rate should I use for forecasting — all deals or qualified deals only? What lookback window (6 months, 12 months)?",
    can_skip: true,
    skip_message: "Got it — I'll use all closed deals with a 6-month lookback. No Stage 0 exclusion.",
    skip_default: { win_rate: { minimum_stage: null, lookback_days: 180 } },
    show_artifact: false,
  },
  {
    id: 'Q8_coverage',
    tier: 1,
    title: 'Coverage Target',
    config_targets: ['thresholds.coverage_target'],
    requires_data: ['deals'],
    requires_questions: ['Q1_motions'],
    trigger: null,
    hypothesis_generator: 'generateCoverageHypothesis',
    prompt_intro: "Here's your current pipeline coverage compared to industry norms:",
    input_hint: "What pipeline coverage multiple are you targeting? 3x? 4x? Does it differ by motion?",
    can_skip: true,
    skip_message: "Got it — I'll use 3x coverage target across all motions.",
    skip_default: { thresholds: { coverage_target: 3.0 } },
    show_artifact: false,
  },
  {
    id: 'Q9_fields',
    tier: 1,
    title: 'Required Fields by Stage',
    config_targets: ['thresholds.required_fields'],
    requires_data: ['deals'],
    requires_questions: ['Q3_stages'],
    trigger: null,
    hypothesis_generator: 'generateRequiredFieldsHypothesis',
    prompt_intro: "I looked at field fill rates by stage. Here's what your team actually fills in:",
    input_hint: "Should I enforce any of these fields by stage? Are there fields your team doesn't use that I shouldn't penalize for being empty?",
    can_skip: true,
    skip_message: "Got it — I'll require amount and close_date as the baseline for all stages.",
    skip_default: { thresholds: { required_fields: ['amount', 'close_date'] } },
    show_artifact: false,
  },
];
