ALTER TABLE deals ADD COLUMN IF NOT EXISTS velocity_score NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS deal_risk NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS deal_risk_factors JSONB NOT NULL DEFAULT '[]';
