-- ============================================================================
-- Add agent_run_id to findings table
-- ============================================================================
-- Created: 2026-02-15
-- Purpose: Support findings extraction from both individual skill runs and agent runs
--
-- Findings can be generated by:
-- 1. Individual skill runs (skill_run_id populated)
-- 2. Agent runs that compose multiple skills (agent_run_id populated)
-- ============================================================================

-- Add agent_run_id column (nullable, since existing findings are from skill runs)
ALTER TABLE findings
ADD COLUMN IF NOT EXISTS agent_run_id UUID REFERENCES agent_runs(id) ON DELETE CASCADE;

-- Add index for agent run queries
CREATE INDEX IF NOT EXISTS idx_findings_agent_run
  ON findings (agent_run_id)
  WHERE agent_run_id IS NOT NULL;

-- Update column to be nullable now that we support two source types
ALTER TABLE findings
ALTER COLUMN skill_run_id DROP NOT NULL;

-- Add comment
COMMENT ON COLUMN findings.agent_run_id IS 'Agent run that generated this finding (via multi-skill composition)';
COMMENT ON COLUMN findings.skill_run_id IS 'Individual skill run that generated this finding (if not from agent)';
