ALTER TABLE deals ADD COLUMN IF NOT EXISTS ai_score INT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS ai_score_updated_at TIMESTAMPTZ;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS ai_score_breakdown JSONB;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS next_steps TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS lead_source TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS icp_fit_score INT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS icp_fit_at TIMESTAMPTZ;
