-- Migration 181: Add 'monte_carlo' to standing_hypotheses source CHECK constraint
-- The portfolio composition hypothesis generated by the Monte Carlo skill is stored here.

DO $$
DECLARE
  constraint_name text;
BEGIN
  SELECT conname INTO constraint_name
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  WHERE t.relname = 'standing_hypotheses'
    AND c.contype = 'c'
    AND pg_get_constraintdef(c.oid) LIKE '%pre_mortem%';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE standing_hypotheses DROP CONSTRAINT %I', constraint_name);
  END IF;
END $$;

ALTER TABLE standing_hypotheses
  ADD CONSTRAINT standing_hypotheses_source_check
  CHECK (source IN ('pre_mortem', 'stack_trace', 'user_confirmed', 'concierge_recommendation', 'monte_carlo'));
