-- Migration 186: Report Documents
-- Stores structured report documents generated by the Orchestrator

CREATE TABLE IF NOT EXISTS report_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id)
    ON DELETE CASCADE,
  agent_run_id UUID,
  document_type TEXT NOT NULL,
  week_label TEXT NOT NULL,
  headline TEXT,
  sections JSONB NOT NULL DEFAULT '[]',
  actions JSONB NOT NULL DEFAULT '[]',
  recommended_next_steps TEXT,
  skills_included TEXT[] NOT NULL DEFAULT '{}',
  skills_omitted TEXT[] NOT NULL DEFAULT '{}',
  total_word_count INTEGER,
  tokens_used INTEGER,
  orchestrator_run_id UUID NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_report_documents_workspace
  ON report_documents(workspace_id, document_type, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_report_documents_week
  ON report_documents(workspace_id, week_label);

CREATE INDEX IF NOT EXISTS idx_report_documents_agent_run
  ON report_documents(agent_run_id)
  WHERE agent_run_id IS NOT NULL;
