/**
 * Deliverables API Endpoints
 *
 * Provides endpoints for generating, previewing, and retrieving template-driven deliverables.
 */

import express from 'express';
import { generateDeliverable } from '../templates/deliverable-pipeline.js';
import { query } from '../db.js';
import { testDocumentGeneration } from '../chat/document-synthesizer.js';
import pool from '../db.js';

const router = express.Router({ mergeParams: true });

/**
 * Parse markdown text into an array of {heading, bullets} sections for slides
 */
function parseContentIntoSections(text: string): Array<{ heading: string; bullets: string[] }> {
  const lines = text.split('\n');
  const sections: Array<{ heading: string; bullets: string[] }> = [];
  let current: { heading: string; bullets: string[] } | null = null;

  for (const line of lines) {
    const hMatch = line.match(/^#{1,3}\s+(.+)/);
    if (hMatch) {
      if (current) sections.push(current);
      current = { heading: hMatch[1].trim(), bullets: [] };
    } else if (current) {
      const clean = line
        .replace(/^\s*[-*•]\s*/, '')
        .replace(/\*\*(.*?)\*\*/g, '$1')
        .replace(/\*(.*?)\*/g, '$1')
        .trim();
      if (clean.length > 4) current.bullets.push(clean);
    }
  }
  if (current) sections.push(current);

  if (sections.length === 0) {
    const paras = text.split(/\n\n+/).map(p => p.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1').trim()).filter(Boolean);
    const chunk = 4;
    for (let i = 0; i < paras.length; i += chunk) {
      sections.push({ heading: i === 0 ? 'Overview' : `Continued`, bullets: paras.slice(i, i + chunk) });
    }
  }

  return sections.slice(0, 10);
}

/**
 * Generate a .pptx from plain text content and store in generated_documents
 */
async function generatePptxFromText(workspaceId: string, title: string, content: string): Promise<string> {
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pptx = new (PptxGenJS as any)();
  pptx.layout = 'LAYOUT_16x9';
  pptx.author = 'Pandora';
  pptx.company = 'Pandora GTM Intelligence';
  pptx.title = title;

  const C = { bg: '0F172A', accent: '3B82F6', white: 'FFFFFF', light: '94A3B8', card: '1E293B' };

  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: C.bg };
  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 4.8, w: 10, h: 0.06, fill: { color: C.accent } });
  titleSlide.addText(title, {
    x: 0.8, y: 1.6, w: 8.4, h: 1.6, fontSize: 36, bold: true, color: C.white, fontFace: 'Calibri',
  });
  titleSlide.addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), {
    x: 0.8, y: 3.3, w: 8.4, h: 0.5, fontSize: 16, color: C.light, fontFace: 'Calibri',
  });
  titleSlide.addText('Generated by Pandora RevOps Intelligence', {
    x: 0.8, y: 4.0, w: 8.4, h: 0.4, fontSize: 12, color: C.light, fontFace: 'Calibri', italic: true,
  });

  const sections = parseContentIntoSections(content);

  for (const section of sections) {
    const slide = pptx.addSlide();
    slide.background = { color: C.bg };
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 10, h: 0.08, fill: { color: C.accent } });
    slide.addText(section.heading, {
      x: 0.6, y: 0.2, w: 8.8, h: 0.7, fontSize: 22, bold: true, color: C.white, fontFace: 'Calibri',
    });

    const visibleBullets = section.bullets.slice(0, 7);
    if (visibleBullets.length > 0) {
      slide.addText(
        visibleBullets.map(b => ({ text: b, options: { bullet: { type: 'bullet' }, fontSize: 14, color: 'E2E8F0', fontFace: 'Calibri', paraSpaceAfter: 6 } })),
        { x: 0.6, y: 1.1, w: 8.8, h: 4.2 }
      );
    }
  }

  const buffer = await pptx.write('nodebuffer') as Buffer;
  const date = new Date().toISOString().slice(0, 10);
  const slug = title.toLowerCase().replace(/[^a-z0-9\s]/g, '').replace(/\s+/g, '-').slice(0, 30);
  const filename = `${workspaceId}-${date}-${slug}.pptx`;

  await pool.query(
    `INSERT INTO generated_documents (workspace_id, filename, content_type, data, file_size)
     VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT (workspace_id, filename) DO UPDATE SET data = $4, file_size = $5, created_at = NOW()`,
    [workspaceId, filename, 'application/vnd.openxmlformats-officedocument.presentationml.presentation', buffer, buffer.length]
  );

  return filename;
}

/**
 * Convert markdown to simple HTML for email
 */
function markdownToHtml(md: string): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: -apple-system, sans-serif; color: #1e293b; max-width: 700px; margin: 40px auto; padding: 0 20px; line-height: 1.6; }
  h1, h2, h3 { color: #0f172a; margin-top: 1.5em; }
  p { margin: 0.75em 0; }
  ul, ol { padding-left: 1.5em; }
  li { margin: 0.3em 0; }
  strong { color: #0f172a; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }
</style></head>
<body>
${md
  .replace(/^### (.+)$/gm, '<h3>$1</h3>')
  .replace(/^## (.+)$/gm, '<h2>$1</h2>')
  .replace(/^# (.+)$/gm, '<h1>$1</h1>')
  .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  .replace(/\*(.+?)\*/g, '<em>$1</em>')
  .replace(/^\- (.+)$/gm, '<li>$1</li>')
  .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
  .replace(/\n\n/g, '</p><p>')
  .replace(/^(?!<[hul])(.+)$/gm, '<p>$1</p>')}
<div class="footer">Sent from Pandora GTM Intelligence · <a href="https://pandora.ai">pandora.ai</a></div>
</body>
</html>`;
}

/**
 * POST /api/workspaces/:workspaceId/deliverables/generate
 *
 * When called with { format, content, title } → generates the specific export.
 * Legacy: when called without format → runs full deliverable matrix pipeline.
 */
router.post('/deliverables/generate', async (req: any, res: any) => {
  const workspaceId = (req.params as any).workspaceId as string;
  const { format, content, title = 'Pandora Analysis', templateType, customDimensions, voiceConfig } = req.body;

  if (!format || !content) {
    try {
      const result = await generateDeliverable({ workspaceId, templateType, customDimensions, voiceConfig });
      return res.json({
        template_type: result.matrix.template_type,
        stages: result.matrix.stages.length,
        dimensions: result.matrix.rows.length,
        cells: result.matrix.cell_count,
        population: result.populationStats,
        matrix: result.matrix,
      });
    } catch (err) {
      console.error('[Deliverable] Generation failed:', err);
      return res.status(500).json({ error: 'Deliverable generation failed', details: (err as Error).message });
    }
  }

  try {
    if (format === 'doc') {
      console.log(`[Deliverables] Generating doc for workspace ${workspaceId} (${content.length} chars)`);
      const synthOutput = await testDocumentGeneration(workspaceId, content);
      return res.json({
        downloadUrl: `/api/workspaces/${workspaceId}/generated-docs/${synthOutput.docxFilename}`,
      });
    }

    if (format === 'slides') {
      console.log(`[Deliverables] Generating slides for workspace ${workspaceId}`);
      const filename = await generatePptxFromText(workspaceId, title, content);
      return res.json({
        downloadUrl: `/api/workspaces/${workspaceId}/generated-docs/${filename}`,
      });
    }

    if (format === 'email') {
      const to: string | undefined = (req as any).user?.email;
      if (!to) {
        return res.status(400).json({ error: 'No email address found for your account' });
      }
      const { Resend } = await import('resend');
      const resend = new Resend(process.env.RESEND_API_KEY);
      const html = markdownToHtml(content);
      await resend.emails.send({
        from: process.env.RESEND_FROM_EMAIL || 'Pandora <onboarding@resend.dev>',
        to,
        subject: `Pandora: ${title}`,
        html,
      });
      console.log(`[Deliverables] Email sent to ${to}`);
      return res.json({ sent: true, to });
    }

    if (format === 'slack') {
      const wsRow = await query(`SELECT settings->>'slack_webhook_url' AS webhook FROM workspaces WHERE id = $1`, [workspaceId]);
      const webhookUrl = wsRow.rows[0]?.webhook;
      if (!webhookUrl) {
        return res.json({ error: 'Slack not connected — add your webhook URL in Settings → Integrations' });
      }
      const slackBody = {
        blocks: [
          { type: 'header', text: { type: 'plain_text', text: `📊 ${title}`, emoji: true } },
          { type: 'section', text: { type: 'mrkdwn', text: content.slice(0, 2800) } },
          { type: 'context', elements: [{ type: 'mrkdwn', text: '_Sent from Pandora GTM Intelligence_' }] },
        ],
      };
      const slackRes = await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(slackBody),
      });
      if (!slackRes.ok) {
        return res.json({ error: `Slack returned ${slackRes.status} — check your webhook URL` });
      }
      console.log(`[Deliverables] Slack message sent for workspace ${workspaceId}`);
      return res.json({ sent: true });
    }

    return res.json({ ok: true, format });
  } catch (err) {
    console.error(`[Deliverable] Export failed (${format}):`, err);
    return res.status(500).json({ error: `Export failed: ${(err as Error).message}` });
  }
});

/**
 * POST /api/workspaces/:workspaceId/deliverables/preview
 */
router.post('/deliverables/preview', async (req, res) => {
  const workspaceId = (req.params as any).workspaceId as string;
  const { templateType, customDimensions } = req.body;

  try {
    const result = await generateDeliverable({ workspaceId, templateType, customDimensions, skipSynthesis: true });
    res.json({
      template_type: result.matrix.template_type,
      stages: result.matrix.stages.map((s: any) => s.stage_name),
      dimensions: result.matrix.rows.map((r: any) => ({ key: r.dimension_key, label: r.dimension_label, source_type: r.source_type })),
      cell_budget: result.discovery.cell_budget,
      excluded_dimensions: result.discovery.excluded_dimensions,
      coverage: result.discovery.coverage,
      timing: { discovery_ms: result.discovery_ms, assembly_ms: result.assembly_ms },
    });
  } catch (err) {
    console.error('[Deliverable] Preview failed:', err);
    res.status(500).json({ error: 'Preview failed', details: (err as Error).message });
  }
});

/**
 * GET /api/workspaces/:workspaceId/deliverables/latest
 */
router.get('/deliverables/latest', async (req, res) => {
  const workspaceId = (req.params as any).workspaceId as string;
  const { templateType = 'sales_process_map' } = req.query;

  try {
    const result = await query(`
      SELECT matrix, discovery, generated_at, total_tokens, cells_populated, cells_degraded
      FROM deliverable_results
      WHERE workspace_id = $1 AND template_type = $2
      ORDER BY generated_at DESC LIMIT 1
    `, [workspaceId, templateType]);

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'No deliverable found. Generate one first.' });
    }

    const row = result.rows[0];
    res.json({
      matrix: row.matrix, discovery: row.discovery, generated_at: row.generated_at,
      stats: { total_tokens: row.total_tokens, cells_populated: row.cells_populated, cells_degraded: row.cells_degraded },
    });
  } catch (err) {
    console.error('[Deliverable] Retrieval failed:', err);
    res.status(500).json({ error: 'Failed to retrieve deliverable', details: (err as Error).message });
  }
});

export default router;
