/**
 * Action Types for Pandora
 *
 * Actions are work items generated by skills that route to different destinations:
 * - Rep-facing actions → CRM + Slack (existing)
 * - Ops-facing actions → PM tools (new)
 */

/**
 * Action types enum
 * Ops actions start with 'ops_' prefix and route to PM tools
 * Rep actions route to CRM/Slack
 */
export type ActionType =
  // Existing rep-facing actions (route to CRM + Slack)
  | 're_engage_deal'
  | 'close_stale_deal'
  | 'update_close_date'
  | 'notify_rep'
  | 'notify_manager'
  | 'escalate_deal'

  // New ops-facing actions (route to PM tools)
  | 'ops_process_fix'         // Sales process needs updating
  | 'ops_system_config'       // CRM/tool configuration change needed
  | 'ops_data_cleanup'        // Bulk data fix or validation rule
  | 'ops_methodology_review'  // Forecast/qualification criteria need review
  | 'ops_enablement_gap'      // Training or playbook needed
  | 'ops_territory_planning'  // Territory/capacity rebalancing needed
  | 'ops_reporting_request'   // Dashboard or report to build
  | 'ops_gtm_strategy';       // Strategic recommendation from ICP/CI data

/**
 * Check if an action type is ops-facing (routes to PM tool)
 */
export function isOpsAction(actionType: ActionType): boolean {
  return actionType.startsWith('ops_');
}

/**
 * Map action type to OpsCategory for PM tools
 */
export function actionTypeToOpsCategory(actionType: ActionType): string {
  if (!isOpsAction(actionType)) {
    throw new Error(`Action type ${actionType} is not an ops action`);
  }

  // Remove 'ops_' prefix to get category
  return actionType.replace('ops_', '');
}
