/**
 * Calibration Questions — Phase 7
 *
 * 100+ question bank for populating calibration_checklist.
 * Every question a skill depends on must be defined here.
 */

// ============================================================
// TYPES
// ============================================================

export interface CalibrationQuestion {
  question_id: string;
  domain: 'business' | 'metrics' | 'taxonomy' | 'pipeline' | 'segmentation' | 'data_quality';
  question: string;
  description: string;
  answer_type: 'text' | 'select' | 'multiselect' | 'boolean' | 'number' | 'field_picker' | 'stage_picker';
  options?: string[];
  depends_on: string[];
  skill_dependencies: string[];
  required_for_live: boolean;
}

// ============================================================
// PIPELINE DOMAIN — 18 questions
// ============================================================

const PIPELINE_QUESTIONS: CalibrationQuestion[] = [
  {
    question_id: 'pipeline_active_stages',
    domain: 'pipeline',
    question: 'Which stages count as active pipeline?',
    description: 'Identifies stages where deals are actively being worked. Used for pipeline reporting, coverage calculations, and velocity tracking. Critical for distinguishing pipeline from closed/disqualified deals.',
    answer_type: 'stage_picker',
    options: [],
    depends_on: [],
    skill_dependencies: [
      'pipeline-waterfall', 'pipeline-coverage', 'forecast-rollup', 'stage-velocity-benchmarks',
      'pipeline-conversion-rate', 'pipeline-progression', 'pipeline-hygiene', 'pipeline-movement',
      'pipeline-gen-forecast', 'pipeline-contribution-forecast', 'deal-risk-review', 'deal-scoring-model',
      'deal-rfm-scoring', 'stage-mismatch-detector', 'behavioral-winning-path', 'monte-carlo-forecast',
      'bowtie-analysis'
    ],
    required_for_live: true,
  },
  {
    question_id: 'pipeline_coverage_target',
    domain: 'pipeline',
    question: 'What is your overall pipeline coverage target?',
    description: 'The ratio of pipeline to quota that represents healthy coverage (e.g., 3.0 = 3x coverage). Used to flag coverage gaps and guide pipeline generation efforts.',
    answer_type: 'number',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['pipeline-waterfall', 'pipeline-coverage', 'pipeline-goals'],
    required_for_live: true,
  },
  {
    question_id: 'coverage_target_by_segment',
    domain: 'pipeline',
    question: 'Do you set different coverage targets per segment?',
    description: 'Whether coverage targets vary by segment (e.g., 4x for new logo, 2.5x for expansion). Enables segment-specific coverage tracking.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['segmentation_field', 'pipeline_coverage_target'],
    skill_dependencies: ['pipeline-coverage'],
    required_for_live: false,
  },
  {
    question_id: 'coverage_requires_segmentation',
    domain: 'pipeline',
    question: 'Must pipeline coverage always be broken down by segment?',
    description: 'Forces segmentation in all pipeline coverage queries. Used when aggregated coverage masks segment-level problems.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['pipeline-waterfall', 'pipeline-coverage'],
    required_for_live: true,
  },
  {
    question_id: 'forecast_categories',
    domain: 'pipeline',
    question: 'What forecast categories do you track?',
    description: 'Standard forecast categorization (e.g., Commit, Best Case, Pipeline, Omitted). Used for forecast rollup, accuracy tracking, and stage-to-category mapping.',
    answer_type: 'multiselect',
    options: ['Commit', 'Best Case', 'Pipeline', 'Most Likely', 'Upside', 'Omitted', 'Closed'],
    depends_on: [],
    skill_dependencies: ['forecast-rollup', 'forecast-accuracy-tracking', 'monte-carlo-forecast', 'pipeline-contribution-forecast', 'forecast-model'],
    required_for_live: true,
  },
  {
    question_id: 'weighted_pipeline',
    domain: 'pipeline',
    question: 'Do you use probability weighting for pipeline?',
    description: 'Whether deals are weighted by probability or stage-based percentages. Affects forecast calculations and pipeline valuation.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['forecast-model', 'pipeline-contribution-forecast'],
    required_for_live: false,
  },
  {
    question_id: 'pipeline_excludes_stages',
    domain: 'pipeline',
    question: 'Are there any stages explicitly excluded from pipeline reporting?',
    description: 'Stages that should never count as pipeline even if open (e.g., Nurture, On Hold, Disqualified but not closed).',
    answer_type: 'stage_picker',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['pipeline-waterfall', 'pipeline-hygiene'],
    required_for_live: false,
  },
  {
    question_id: 'commit_criteria',
    domain: 'pipeline',
    question: 'What criteria determine if a deal is in Commit forecast?',
    description: 'Business rules for Commit categorization (e.g., stage + probability, manual override, champion validated). Used for forecast rollup.',
    answer_type: 'text',
    options: [],
    depends_on: ['forecast_categories'],
    skill_dependencies: ['forecast-rollup', 'forecast-model'],
    required_for_live: false,
  },
  {
    question_id: 'at_risk_definition',
    domain: 'pipeline',
    question: 'How do you define an at-risk deal?',
    description: 'Criteria for flagging deals as at-risk (e.g., no activity in 30 days, close date pushed 3+ times, missing next steps). Used by pipeline hygiene and deal risk review.',
    answer_type: 'text',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['pipeline-hygiene', 'deal-risk-review'],
    required_for_live: false,
  },
  {
    question_id: 'pipeline_review_cadence',
    domain: 'pipeline',
    question: 'How often do you conduct pipeline reviews?',
    description: 'Frequency of formal pipeline inspection (Weekly, Bi-weekly, Monthly). Informs when pipeline hygiene alerts should fire.',
    answer_type: 'select',
    options: ['Daily', 'Weekly', 'Bi-weekly', 'Monthly'],
    depends_on: [],
    skill_dependencies: ['pipeline-hygiene', 'weekly-recap'],
    required_for_live: false,
  },
  {
    question_id: 'stale_deal_threshold',
    domain: 'pipeline',
    question: 'After how many days without activity is a deal considered stale?',
    description: 'Number of days with no activity before a deal is flagged for hygiene review. Typically 14-30 days.',
    answer_type: 'number',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['pipeline-hygiene', 'deal-risk-review'],
    required_for_live: false,
  },
  {
    question_id: 'pipeline_creation_source',
    domain: 'pipeline',
    question: 'How is pipeline primarily sourced?',
    description: 'Primary pipeline creation method (Inbound, Outbound, Partner, Channel). Used for pipeline gen forecast and contribution analysis.',
    answer_type: 'multiselect',
    options: ['Inbound', 'Outbound SDR', 'Outbound AE', 'Partner', 'Channel', 'Expansion'],
    depends_on: [],
    skill_dependencies: ['pipeline-gen-forecast', 'pipeline-movement'],
    required_for_live: false,
  },
  {
    question_id: 'push_threshold',
    domain: 'pipeline',
    question: 'How many times can a close date be pushed before it\'s considered a red flag?',
    description: 'Number of close date changes that trigger deal health concerns. Used for at-risk detection.',
    answer_type: 'number',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-hygiene', 'deal-risk-review'],
    required_for_live: false,
  },
  {
    question_id: 'pipeline_stage_order',
    domain: 'pipeline',
    question: 'What is the standard stage progression order?',
    description: 'Sequential order of stages from first contact to close. Used for stage mismatch detection and progression tracking.',
    answer_type: 'text',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['stage-mismatch-detector', 'pipeline-progression'],
    required_for_live: false,
  },
  {
    question_id: 'best_case_criteria',
    domain: 'pipeline',
    question: 'What moves a deal from Pipeline to Best Case?',
    description: 'Business logic for Best Case forecast categorization. Used for forecast rollup and accuracy tracking.',
    answer_type: 'text',
    options: [],
    depends_on: ['forecast_categories'],
    skill_dependencies: ['forecast-rollup', 'forecast-model'],
    required_for_live: false,
  },
  {
    question_id: 'multi_stage_entry',
    domain: 'pipeline',
    question: 'Can deals enter pipeline at stages other than Stage 1?',
    description: 'Whether deals can skip early stages (common for expansion, partner deals). Affects velocity benchmarks and conversion tracking.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['stage-velocity-benchmarks', 'pipeline-progression'],
    required_for_live: false,
  },
  {
    question_id: 'pipeline_ownership',
    domain: 'pipeline',
    question: 'Who owns pipeline generation targets?',
    description: 'Team responsible for hitting pipeline creation goals (AE, SDR, Marketing, Hybrid). Used for pipeline gen forecast accountability.',
    answer_type: 'select',
    options: ['Account Executives', 'SDRs', 'Marketing', 'Hybrid AE+SDR', 'Customer Success'],
    depends_on: [],
    skill_dependencies: ['pipeline-gen-forecast', 'pipeline-goals'],
    required_for_live: false,
  },
  {
    question_id: 'pipeline_includes_renewals',
    domain: 'pipeline',
    question: 'Are renewals included in pipeline reporting?',
    description: 'Whether renewal opportunities count toward pipeline coverage. Affects segmentation and coverage targets.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['pipeline-waterfall', 'pipeline-coverage'],
    required_for_live: false,
  },
];

// ============================================================
// SEGMENTATION DOMAIN — 12 questions
// ============================================================

const SEGMENTATION_QUESTIONS: CalibrationQuestion[] = [
  {
    question_id: 'segmentation_field',
    domain: 'segmentation',
    question: 'Which field segments your business?',
    description: 'Primary dimension for breaking down metrics (e.g., Deal Type, Region, Segment, Product Line). Used across all segmented reporting.',
    answer_type: 'field_picker',
    options: [],
    depends_on: [],
    skill_dependencies: [
      'pipeline-waterfall', 'pipeline-coverage', 'rep-scorecard', 'stage-velocity-benchmarks',
      'pipeline-conversion-rate', 'pipeline-progression', 'pipeline-goals', 'pipeline-contribution-forecast',
      'gtm-health-diagnostic'
    ],
    required_for_live: true,
  },
  {
    question_id: 'segmentation_values',
    domain: 'segmentation',
    question: 'What are the segment values?',
    description: 'Actual values for the segmentation field (e.g., ["New Logo", "Expansion"] or ["East", "West", "EMEA"]). Used to validate segment references.',
    answer_type: 'multiselect',
    options: [],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['pipeline-waterfall', 'pipeline-coverage'],
    required_for_live: true,
  },
  {
    question_id: 'segmentation_entity',
    domain: 'segmentation',
    question: 'Does the segment field live on Deal, Company, or Contact?',
    description: 'Entity where segmentation field exists. Determines JOIN strategy for segmented queries.',
    answer_type: 'select',
    options: ['deal', 'company', 'contact'],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['pipeline-coverage', 'rep-scorecard'],
    required_for_live: true,
  },
  {
    question_id: 'primary_segmentation_dimension',
    domain: 'segmentation',
    question: 'What is your primary reporting dimension?',
    description: 'The main lens through which leadership views the business (Geography, Product, Deal Type, Segment). Informs default segmentation.',
    answer_type: 'select',
    options: ['Geography', 'Product Line', 'Deal Type', 'Customer Segment', 'Industry', 'Team/Rep'],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'secondary_segmentation',
    domain: 'segmentation',
    question: 'Do you use a secondary segmentation dimension?',
    description: 'Whether reporting requires two-level segmentation (e.g., Region + Deal Type). Used for multi-dimensional analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['pipeline-coverage', 'rep-scorecard'],
    required_for_live: false,
  },
  {
    question_id: 'secondary_segment_field',
    domain: 'segmentation',
    question: 'What is the secondary segment field?',
    description: 'Second-level segmentation field when multi-dimensional analysis is required.',
    answer_type: 'field_picker',
    options: [],
    depends_on: ['secondary_segmentation'],
    skill_dependencies: ['pipeline-coverage', 'rep-scorecard'],
    required_for_live: false,
  },
  {
    question_id: 'segment_specific_quotas',
    domain: 'segmentation',
    question: 'Are quotas set per segment?',
    description: 'Whether each segment has its own quota target. Affects coverage and attainment calculations.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['pipeline-goals', 'rep-scorecard', 'quarterly-pre-mortem'],
    required_for_live: false,
  },
  {
    question_id: 'segment_creation_process',
    domain: 'segmentation',
    question: 'How are new segment values created?',
    description: 'Process for adding new segments (Admin-controlled, Automatically from CRM, User-defined picklist). Affects data quality and validation.',
    answer_type: 'select',
    options: ['Admin-controlled', 'CRM picklist', 'Free text', 'Formula field'],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['workspace-config-audit', 'data-quality-audit'],
    required_for_live: false,
  },
  {
    question_id: 'segment_required_field',
    domain: 'segmentation',
    question: 'Is the segmentation field required on all deals?',
    description: 'Whether segmentation field is mandatory. Affects data completeness and null handling in segmented queries.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['data-quality-audit', 'pipeline-coverage'],
    required_for_live: false,
  },
  {
    question_id: 'segment_default_value',
    domain: 'segmentation',
    question: 'What is the default segment value for deals without one?',
    description: 'Fallback value when segmentation field is null (e.g., "Unassigned", "Other"). Used for null coalescing in queries.',
    answer_type: 'text',
    options: [],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['pipeline-coverage', 'rep-scorecard'],
    required_for_live: false,
  },
  {
    question_id: 'segment_hierarchy',
    domain: 'segmentation',
    question: 'Is there a segment hierarchy (e.g., Region > Territory)?',
    description: 'Whether segments roll up into parent categories. Used for hierarchical reporting and aggregation.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['rep-scorecard', 'forecast-rollup'],
    required_for_live: false,
  },
  {
    question_id: 'segment_acv_variance',
    domain: 'segmentation',
    question: 'Do different segments have significantly different ACV/deal sizes?',
    description: 'Whether segment-level deal size variance is high enough to warrant separate benchmarks. Informs segmentation strategy.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['segmentation_field'],
    skill_dependencies: ['rep-scorecard', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
];

// ============================================================
// TAXONOMY DOMAIN — 18 questions
// ============================================================

const TAXONOMY_QUESTIONS: CalibrationQuestion[] = [
  {
    question_id: 'land_motion_field',
    domain: 'taxonomy',
    question: 'Which field identifies new logo deals?',
    description: 'Field that distinguishes new customer acquisitions (e.g., Deal Type, Opportunity Type). Critical for land vs expand analysis.',
    answer_type: 'field_picker',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'pipeline-conversion-rate', 'icp-taxonomy-builder', 'bowtie-analysis'],
    required_for_live: true,
  },
  {
    question_id: 'land_motion_values',
    domain: 'taxonomy',
    question: 'What values indicate a new logo deal?',
    description: 'Field values that identify new customer deals (e.g., ["New Business", "New Customer"]). Used for land motion filtering.',
    answer_type: 'multiselect',
    options: [],
    depends_on: ['land_motion_field'],
    skill_dependencies: ['rep-scorecard', 'pipeline-conversion-rate', 'bowtie-analysis'],
    required_for_live: true,
  },
  {
    question_id: 'expand_motion_field',
    domain: 'taxonomy',
    question: 'Which field identifies expansion deals?',
    description: 'Field that marks upsell/cross-sell opportunities. Used for expansion rate and bowtie analysis.',
    answer_type: 'field_picker',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'pipeline-conversion-rate', 'icp-taxonomy-builder', 'bowtie-analysis'],
    required_for_live: true,
  },
  {
    question_id: 'expand_motion_values',
    domain: 'taxonomy',
    question: 'What values indicate an expansion deal?',
    description: 'Field values for expansion opportunities (e.g., ["Upsell", "Cross-sell", "Add-on"]). Used for expand motion filtering.',
    answer_type: 'multiselect',
    options: [],
    depends_on: ['expand_motion_field'],
    skill_dependencies: ['rep-scorecard', 'pipeline-conversion-rate', 'bowtie-analysis'],
    required_for_live: true,
  },
  {
    question_id: 'renew_motion_field',
    domain: 'taxonomy',
    question: 'Which field identifies renewal deals (if tracked separately)?',
    description: 'Field for renewal opportunities if tracked in CRM pipeline. Used for NRR calculation and bowtie analysis.',
    answer_type: 'field_picker',
    options: [],
    depends_on: [],
    skill_dependencies: ['bowtie-analysis'],
    required_for_live: false,
  },
  {
    question_id: 'renew_motion_values',
    domain: 'taxonomy',
    question: 'What values indicate a renewal deal?',
    description: 'Field values for renewal opportunities (e.g., ["Renewal", "Renewal - Flat", "Renewal - Expansion"]). Used for renewal tracking.',
    answer_type: 'multiselect',
    options: [],
    depends_on: ['renew_motion_field'],
    skill_dependencies: ['bowtie-analysis'],
    required_for_live: false,
  },
  {
    question_id: 'custom_deal_type_aliases',
    domain: 'taxonomy',
    question: 'Are there any custom deal type names or aliases we should know about?',
    description: 'Non-standard deal type labels (e.g., "SOW" for Statement of Work, "POC" for Proof of Concept). Used for taxonomy normalization.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['icp-taxonomy-builder', 'custom-field-discovery'],
    required_for_live: false,
  },
  {
    question_id: 'multi_product_deals',
    domain: 'taxonomy',
    question: 'Do you sell multiple products that get tracked separately?',
    description: 'Whether product mix is captured at deal level. Affects product-level metrics and ICP analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'icp-discovery'],
    required_for_live: false,
  },
  {
    question_id: 'product_field',
    domain: 'taxonomy',
    question: 'Which field captures product information on deals?',
    description: 'Field that identifies which product(s) are being sold. Used for product-level reporting.',
    answer_type: 'field_picker',
    options: [],
    depends_on: ['multi_product_deals'],
    skill_dependencies: ['rep-scorecard', 'icp-discovery'],
    required_for_live: false,
  },
  {
    question_id: 'pilot_classification',
    domain: 'taxonomy',
    question: 'How do you classify pilot or trial deals?',
    description: 'Whether pilots have separate deal type or stage. Affects pipeline classification and conversion tracking.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['icp-taxonomy-builder', 'pipeline-conversion-rate'],
    required_for_live: false,
  },
  {
    question_id: 'poc_classification',
    domain: 'taxonomy',
    question: 'How do you track Proof of Concept (POC) engagements?',
    description: 'Whether POCs are deals, stages, or separate records. Used for POC conversion tracking.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['icp-taxonomy-builder', 'pipeline-progression'],
    required_for_live: false,
  },
  {
    question_id: 'cross_sell_tracking',
    domain: 'taxonomy',
    question: 'How are cross-sells distinguished from upsells?',
    description: 'Method for separating cross-sell (new product) from upsell (more of same product). Used for expansion analysis.',
    answer_type: 'text',
    options: [],
    depends_on: ['expand_motion_field'],
    skill_dependencies: ['bowtie-analysis', 'icp-taxonomy-builder'],
    required_for_live: false,
  },
  {
    question_id: 'professional_services_deals',
    domain: 'taxonomy',
    question: 'Are professional services sold as separate deals?',
    description: 'Whether PS/implementation revenue has separate opportunities. Affects deal size and product mix analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'icp-discovery'],
    required_for_live: false,
  },
  {
    question_id: 'deal_type_required',
    domain: 'taxonomy',
    question: 'Is deal type a required field on all opportunities?',
    description: 'Whether land/expand/renew classification is mandatory. Affects data completeness.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['land_motion_field'],
    skill_dependencies: ['data-quality-audit', 'bowtie-analysis'],
    required_for_live: false,
  },
  {
    question_id: 'downsell_tracking',
    domain: 'taxonomy',
    question: 'Do you track downsells or contractions in CRM pipeline?',
    description: 'Whether negative ARR changes create opportunities. Used for NRR and churn analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['bowtie-analysis'],
    required_for_live: false,
  },
  {
    question_id: 'partner_deals_classification',
    domain: 'taxonomy',
    question: 'How do you classify partner-sourced deals?',
    description: 'Whether partner deals have special taxonomy (field, type, stage). Used for attribution and ICP analysis.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['icp-discovery', 'pipeline-movement'],
    required_for_live: false,
  },
  {
    question_id: 'expansion_motion_ownership',
    domain: 'taxonomy',
    question: 'Who owns expansion opportunities?',
    description: 'Team responsible for expansion deals (AE, CSM, Hybrid). Affects ownership-based reporting.',
    answer_type: 'select',
    options: ['Account Executive', 'Customer Success', 'Hybrid AE+CS', 'Dedicated Expansion Team'],
    depends_on: ['expand_motion_field'],
    skill_dependencies: ['bowtie-analysis', 'rep-scorecard'],
    required_for_live: false,
  },
  {
    question_id: 'multi_year_deal_handling',
    domain: 'taxonomy',
    question: 'How do you handle multi-year deal values?',
    description: 'Whether multi-year deals are recorded as TCV, ACV, or Year 1 only. Affects revenue recognition and metrics.',
    answer_type: 'select',
    options: ['Total Contract Value (TCV)', 'Annual Contract Value (ACV)', 'Year 1 Value Only', 'Split by year'],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'attainment', 'forecast-rollup'],
    required_for_live: false,
  },
];

// ============================================================
// METRICS DOMAIN — 24 questions
// ============================================================

const METRICS_QUESTIONS: CalibrationQuestion[] = [
  {
    question_id: 'win_rate_denominator',
    domain: 'metrics',
    question: 'How is win rate calculated?',
    description: 'Denominator for win rate calculation. Closed Won vs All Closed (won+lost) is most common. Used across all win rate metrics.',
    answer_type: 'select',
    options: ['closed_won_vs_all_closed', 'closed_won_vs_all_entered', 'closed_won_vs_all_created'],
    depends_on: [],
    skill_dependencies: ['pipeline-conversion-rate', 'monte-carlo-forecast'],
    required_for_live: true,
  },
  {
    question_id: 'attainment_method',
    domain: 'metrics',
    question: 'What is your quota currency?',
    description: 'Primary metric for quota and attainment (ARR, Bookings, Revenue). Determines how attainment is calculated.',
    answer_type: 'select',
    options: ['arr', 'bookings', 'revenue'],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'coaching'],
    required_for_live: true,
  },
  {
    question_id: 'quota_currency',
    domain: 'metrics',
    question: 'What is your quota currency? (Alias of attainment_method)',
    description: 'Duplicate of attainment_method for backward compatibility. Primary quota metric.',
    answer_type: 'select',
    options: ['arr', 'bookings', 'revenue'],
    depends_on: ['attainment_method'],
    skill_dependencies: ['pipeline-goals', 'quarterly-pre-mortem', 'forecast-model'],
    required_for_live: true,
  },
  {
    question_id: 'arr_field',
    domain: 'metrics',
    question: 'Which field represents ARR on deals?',
    description: 'Primary ARR field. Used for ARR-based metrics, NRR calculations, and attainment when quota_currency = ARR.',
    answer_type: 'field_picker',
    options: [],
    depends_on: [],
    skill_dependencies: ['bowtie-analysis', 'rep-scorecard'],
    required_for_live: true,
  },
  {
    question_id: 'arr_decomposed',
    domain: 'metrics',
    question: 'Is ARR stored as a single field or decomposed into components?',
    description: 'Whether ARR is one field or split into New ARR, Expansion ARR, Renewal ARR, Churn ARR. Required for accurate NRR calculation.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['arr_field'],
    skill_dependencies: ['bowtie-analysis'],
    required_for_live: true,
  },
  {
    question_id: 'arr_component_fields',
    domain: 'metrics',
    question: 'If ARR is decomposed, what are the component fields?',
    description: 'Field names for ARR components (e.g., New ARR, Expansion ARR, Contraction ARR). Used for precise NRR calculation.',
    answer_type: 'multiselect',
    options: [],
    depends_on: ['arr_decomposed'],
    skill_dependencies: ['bowtie-analysis'],
    required_for_live: false,
  },
  {
    question_id: 'forecast_methodology',
    domain: 'metrics',
    question: 'What forecasting approach do you use?',
    description: 'Bottom-up (rep-level), top-down (stage/probability), or category-based (commit/best case). Affects forecast aggregation.',
    answer_type: 'select',
    options: ['bottom_up', 'top_down', 'category_based'],
    depends_on: [],
    skill_dependencies: ['forecast-rollup', 'forecast-model', 'quarterly-pre-mortem'],
    required_for_live: true,
  },
  {
    question_id: 'sales_cycle_start',
    domain: 'metrics',
    question: 'When does the sales cycle begin?',
    description: 'Starting point for sales cycle calculation (Deal Created, Stage 1 Entry, First Meeting). Affects velocity benchmarks.',
    answer_type: 'select',
    options: ['deal_created', 'stage_1_entered', 'first_meeting', 'sql_date'],
    depends_on: [],
    skill_dependencies: ['stage-velocity-benchmarks', 'pipeline-progression'],
    required_for_live: false,
  },
  {
    question_id: 'nrr_tracked',
    domain: 'metrics',
    question: 'Do you actively track Net Revenue Retention (NRR)?',
    description: 'Whether NRR is a board-level metric. Determines if NRR-related skills are relevant.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['bowtie-analysis', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'mql_definition',
    domain: 'metrics',
    question: 'How is a Marketing Qualified Lead (MQL) defined?',
    description: 'Criteria for MQL status (scoring threshold, engagement level, form submission). Used for MQL-to-SQL conversion tracking.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-movement', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'sql_definition',
    domain: 'metrics',
    question: 'How is a Sales Qualified Lead (SQL) defined?',
    description: 'Criteria for SQL acceptance (discovery call held, BANT criteria, opportunity created). Used for conversion funnel.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-movement', 'lead-scoring'],
    required_for_live: false,
  },
  {
    question_id: 'opportunity_source_tracking',
    domain: 'metrics',
    question: 'Do you track lead/opportunity source in CRM?',
    description: 'Whether source attribution (Inbound, Outbound, Partner) is captured. Affects pipeline contribution analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-gen-forecast', 'pipeline-movement'],
    required_for_live: false,
  },
  {
    question_id: 'average_contract_length',
    domain: 'metrics',
    question: 'What is the typical contract length?',
    description: 'Standard contract term (12 months, 24 months, 36 months). Used for ACV/TCV normalization.',
    answer_type: 'select',
    options: ['6 months', '12 months', '24 months', '36 months', 'Varies significantly'],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'forecast-model'],
    required_for_live: false,
  },
  {
    question_id: 'renewal_rate_target',
    domain: 'metrics',
    question: 'What is your target renewal rate?',
    description: 'Goal for renewal/retention rate (typically 85-95% for SaaS). Used for churn and NRR analysis.',
    answer_type: 'number',
    options: [],
    depends_on: [],
    skill_dependencies: ['bowtie-analysis', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'contraction_tracking',
    domain: 'metrics',
    question: 'Do you actively track and report on contraction/downsell?',
    description: 'Whether negative ARR changes are monitored separately from full churn. Affects NRR decomposition.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['bowtie-analysis'],
    required_for_live: false,
  },
  {
    question_id: 'tcv_vs_acv_reporting',
    domain: 'metrics',
    question: 'Do you report Total Contract Value (TCV) or Annual Contract Value (ACV)?',
    description: 'Primary deal value metric for reporting. Affects how multi-year deals are valued.',
    answer_type: 'select',
    options: ['TCV only', 'ACV only', 'Both TCV and ACV', 'Year 1 value'],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'forecast-rollup'],
    required_for_live: false,
  },
  {
    question_id: 'activity_metrics_tracked',
    domain: 'metrics',
    question: 'Which activity metrics do you actively track?',
    description: 'Activity KPIs monitored for rep performance (Calls, Meetings, Emails, Demos). Used for activity-based coaching.',
    answer_type: 'multiselect',
    options: ['Calls', 'Meetings', 'Emails', 'Demos', 'Proposals sent', 'None'],
    depends_on: [],
    skill_dependencies: ['coaching', 'rep-scorecard'],
    required_for_live: false,
  },
  {
    question_id: 'pipeline_velocity_calculation',
    domain: 'metrics',
    question: 'How do you calculate pipeline velocity?',
    description: 'Formula for velocity metric (e.g., Pipeline × Win Rate × Avg Deal Size / Sales Cycle). Used for velocity benchmarking.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-progression', 'stage-velocity-benchmarks'],
    required_for_live: false,
  },
  {
    question_id: 'stage_probability_mapping',
    domain: 'metrics',
    question: 'Do stages have associated probability percentages?',
    description: 'Whether each stage maps to a win probability (e.g., Demo = 20%, Proposal = 60%). Used for weighted pipeline.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['pipeline_active_stages'],
    skill_dependencies: ['forecast-model', 'monte-carlo-forecast'],
    required_for_live: false,
  },
  {
    question_id: 'rep_ramp_period',
    domain: 'metrics',
    question: 'What is the expected ramp period for new reps?',
    description: 'Number of months for new rep to reach full productivity (typically 3-6 months). Used for attainment normalization.',
    answer_type: 'number',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'coaching'],
    required_for_live: false,
  },
  {
    question_id: 'quota_attainment_threshold',
    domain: 'metrics',
    question: 'What quota attainment percentage is considered hitting quota?',
    description: 'Threshold for "making quota" (typically 90-100%). Used for attainment distribution calculations.',
    answer_type: 'number',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'coaching'],
    required_for_live: false,
  },
  {
    question_id: 'churn_calculation_method',
    domain: 'metrics',
    question: 'How is churn calculated?',
    description: 'Method for churn rate (Logo churn, ARR churn, MRR churn). Affects retention and NRR analysis.',
    answer_type: 'select',
    options: ['Logo churn rate', 'ARR/MRR churn rate', 'Revenue retention', 'Customer count'],
    depends_on: [],
    skill_dependencies: ['bowtie-analysis', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'pipeline_aging_buckets',
    domain: 'metrics',
    question: 'How do you bucket pipeline by age?',
    description: 'Age ranges for pipeline aging analysis (e.g., 0-30, 31-60, 61-90, 90+ days). Used for hygiene reporting.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-hygiene', 'deal-risk-review'],
    required_for_live: false,
  },
  {
    question_id: 'bookings_vs_revenue_recognition',
    domain: 'metrics',
    question: 'Do you differentiate bookings from recognized revenue?',
    description: 'Whether bookings (deal signed) differs from revenue recognition timing. Affects financial metrics.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'forecast-rollup'],
    required_for_live: false,
  },
];

// ============================================================
// BUSINESS DOMAIN — 18 questions
// ============================================================

const BUSINESS_QUESTIONS: CalibrationQuestion[] = [
  {
    question_id: 'gtm_motion',
    domain: 'business',
    question: 'What is your primary go-to-market motion?',
    description: 'Primary growth strategy (New Logo, Expansion, Hybrid). Used for context in strategy recommendations.',
    answer_type: 'select',
    options: ['new_logo', 'expansion', 'hybrid'],
    depends_on: [],
    skill_dependencies: ['strategy-insights', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'growth_stage',
    domain: 'business',
    question: 'What stage of growth is your company in?',
    description: 'Maturity level (Early = seed/A, Scaling = B/C, Mature = D+/public). Informs benchmarks and recommendations.',
    answer_type: 'select',
    options: ['early', 'scaling', 'mature'],
    depends_on: [],
    skill_dependencies: ['strategy-insights', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'revenue_model',
    domain: 'business',
    question: 'What is your primary revenue model?',
    description: 'How revenue is recognized (ARR subscription, Bookings upfront, Usage-based). Affects metric definitions.',
    answer_type: 'select',
    options: ['arr', 'bookings', 'usage'],
    depends_on: [],
    skill_dependencies: ['gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'cro_primary_concern',
    domain: 'business',
    question: 'What is the CRO most focused on right now?',
    description: 'Current top priority for revenue leadership (Predictability, Pipeline gen, Win rate, etc.). Used for contextual recommendations.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['strategy-insights', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'board_metrics',
    domain: 'business',
    question: 'What metrics get reported to the board?',
    description: 'Key metrics shown in board decks (e.g., NRR, Pipeline Coverage, Win Rate). Informs priority of metric accuracy.',
    answer_type: 'multiselect',
    options: ['Pipeline Coverage', 'Win Rate', 'NRR', 'Attainment', 'Sales Cycle', 'ACV', 'Churn'],
    depends_on: [],
    skill_dependencies: ['gtm-health-diagnostic', 'quarterly-pre-mortem'],
    required_for_live: false,
  },
  {
    question_id: 'fiscal_year_start',
    domain: 'business',
    question: 'When does your fiscal year start?',
    description: 'FY start month (typically Jan or Feb for calendar year). Used for YTD calculations and quarter alignment.',
    answer_type: 'select',
    options: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    depends_on: [],
    skill_dependencies: ['forecast-rollup', 'quarterly-pre-mortem'],
    required_for_live: false,
  },
  {
    question_id: 'qbr_cadence',
    domain: 'business',
    question: 'How often do you conduct Quarterly Business Reviews?',
    description: 'Frequency of formal QBRs. Affects when quarterly insights should be generated.',
    answer_type: 'select',
    options: ['Quarterly', 'Monthly', 'Bi-annually', 'Annually', 'Ad-hoc'],
    depends_on: [],
    skill_dependencies: ['quarterly-pre-mortem', 'strategy-insights'],
    required_for_live: false,
  },
  {
    question_id: 'team_structure',
    domain: 'business',
    question: 'How is your sales team structured?',
    description: 'Organizational model (Territory-based, Pod-based, Vertical/Industry, Full-cycle AEs). Affects ownership-based reporting.',
    answer_type: 'select',
    options: ['Territory-based', 'Pod-based (AE+SDR)', 'Industry vertical', 'Full-cycle AEs', 'Hybrid'],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'coaching'],
    required_for_live: false,
  },
  {
    question_id: 'inbound_vs_outbound_mix',
    domain: 'business',
    question: 'What percentage of pipeline is inbound vs outbound?',
    description: 'Rough split of inbound (marketing-sourced) vs outbound (SDR/AE-sourced). Informs pipeline generation strategy.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-gen-forecast', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'primary_competitive_threats',
    domain: 'business',
    question: 'Who are your top 3 competitors?',
    description: 'Main competitive alternatives. Used for competitive intelligence analysis.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['competitive-intelligence', 'strategy-insights'],
    required_for_live: false,
  },
  {
    question_id: 'deal_approval_required',
    domain: 'business',
    question: 'Do deals require approval before closing?',
    description: 'Whether deals need manager/VP approval above certain thresholds. Affects close process tracking.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-hygiene', 'deal-risk-review'],
    required_for_live: false,
  },
  {
    question_id: 'discount_approval_threshold',
    domain: 'business',
    question: 'What discount percentage requires approval?',
    description: 'Threshold where discounting needs manager sign-off. Used for deal risk detection.',
    answer_type: 'number',
    options: [],
    depends_on: [],
    skill_dependencies: ['deal-risk-review', 'deal-scoring-model'],
    required_for_live: false,
  },
  {
    question_id: 'ideal_close_within_quarter',
    domain: 'business',
    question: 'What percentage of pipeline should close within the quarter?',
    description: 'Expected within-quarter close rate. Used for pipeline sufficiency calculations.',
    answer_type: 'number',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-goals', 'forecast-rollup'],
    required_for_live: false,
  },
  {
    question_id: 'sales_compensation_model',
    domain: 'business',
    question: 'What is the primary compensation structure?',
    description: 'How reps are paid (Base + commission, OTE-based, Accelerators). Informs behavior analysis.',
    answer_type: 'select',
    options: ['Base + Commission', 'OTE with accelerators', 'Salary only', 'Draw against commission', 'Tiered commission'],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'coaching'],
    required_for_live: false,
  },
  {
    question_id: 'multi_product_sales',
    domain: 'business',
    question: 'Do you sell multiple distinct products?',
    description: 'Whether company has multiple product lines with separate pricing. Affects product mix analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['icp-discovery', 'rep-scorecard'],
    required_for_live: false,
  },
  {
    question_id: 'renewal_team_ownership',
    domain: 'business',
    question: 'Who manages customer renewals?',
    description: 'Team responsible for renewal process (Sales, CS, Automated). Affects renewal tracking approach.',
    answer_type: 'select',
    options: ['Account Executives', 'Customer Success', 'Renewal Specialists', 'Automated/Self-serve'],
    depends_on: [],
    skill_dependencies: ['bowtie-analysis', 'gtm-health-diagnostic'],
    required_for_live: false,
  },
  {
    question_id: 'target_customer_segment',
    domain: 'business',
    question: 'What is your ideal customer profile (ICP)?',
    description: 'Description of target customer segment (company size, industry, persona). Used for ICP discovery and win path analysis.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['icp-discovery', 'lead-scoring'],
    required_for_live: false,
  },
  {
    question_id: 'average_sales_cycle_target',
    domain: 'business',
    question: 'What is your target average sales cycle length?',
    description: 'Goal for average days to close (typically 30-180 days for B2B SaaS). Used for velocity benchmarking.',
    answer_type: 'number',
    options: [],
    depends_on: [],
    skill_dependencies: ['stage-velocity-benchmarks', 'pipeline-progression'],
    required_for_live: false,
  },
];

// ============================================================
// DATA QUALITY DOMAIN — 18 questions
// ============================================================

const DATA_QUALITY_QUESTIONS: CalibrationQuestion[] = [
  {
    question_id: 'stage_history_tracked',
    domain: 'data_quality',
    question: 'Is stage history available in your CRM?',
    description: 'Whether deal_stage_history table exists with timestamps for each stage transition. Required for velocity and conversion analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['stage-velocity-benchmarks', 'pipeline-progression'],
    required_for_live: true,
  },
  {
    question_id: 'close_dates_reliable',
    domain: 'data_quality',
    question: 'Are close dates maintained accurately?',
    description: 'Whether close dates are consistently updated and reflect real expectations. Affects forecast accuracy and velocity calculations.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['forecast-rollup', 'pipeline-hygiene'],
    required_for_live: false,
  },
  {
    question_id: 'next_steps_required',
    domain: 'data_quality',
    question: 'Is "Next Steps" a required field on active deals?',
    description: 'Whether next steps field is mandatory. Used for deal health and hygiene scoring.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-hygiene', 'deal-risk-review'],
    required_for_live: false,
  },
  {
    question_id: 'deal_amount_field',
    domain: 'data_quality',
    question: 'Which field is the primary deal amount?',
    description: 'Standard field for deal size (Amount, ARR, TCV, etc.). Used for all revenue calculations.',
    answer_type: 'field_picker',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'forecast-rollup', 'pipeline-coverage'],
    required_for_live: true,
  },
  {
    question_id: 'owner_field',
    domain: 'data_quality',
    question: 'Which field represents the deal owner?',
    description: 'Standard owner field for attainment and segmentation. Used for ownership-based reporting.',
    answer_type: 'field_picker',
    options: [],
    depends_on: [],
    skill_dependencies: ['rep-scorecard', 'forecast-rollup'],
    required_for_live: false,
  },
  {
    question_id: 'crm_data_since',
    domain: 'data_quality',
    question: 'How far back does reliable CRM data go?',
    description: 'Earliest date where data is trustworthy (e.g., "2022-01-01"). Used to filter historical queries.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['data-quality-audit', 'stage-velocity-benchmarks'],
    required_for_live: false,
  },
  {
    question_id: 'known_bad_periods',
    domain: 'data_quality',
    question: 'Are there any known data gaps or bad data periods?',
    description: 'Date ranges to exclude from analysis (CRM migration, data loss, incomplete import). Used for query filtering.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['data-quality-audit', 'workspace-config-audit'],
    required_for_live: false,
  },
  {
    question_id: 'custom_field_completion_rate',
    domain: 'data_quality',
    question: 'What is the average completion rate for custom fields?',
    description: 'Percentage of deals with custom fields populated. Indicates data discipline and field utility.',
    answer_type: 'number',
    options: [],
    depends_on: [],
    skill_dependencies: ['data-quality-audit', 'custom-field-discovery'],
    required_for_live: false,
  },
  {
    question_id: 'contact_association_quality',
    domain: 'data_quality',
    question: 'Are contacts consistently associated with deals?',
    description: 'Whether contact relationships are maintained. Affects single-thread detection and ICP analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['single-thread-alert', 'contact-role-resolution'],
    required_for_live: false,
  },
  {
    question_id: 'company_association_quality',
    domain: 'data_quality',
    question: 'Are companies consistently associated with deals?',
    description: 'Whether deal-to-company relationships exist. Required for company-level segmentation.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['icp-discovery', 'data-quality-audit'],
    required_for_live: false,
  },
  {
    question_id: 'deal_source_tracking_quality',
    domain: 'data_quality',
    question: 'Is deal source reliably captured?',
    description: 'Whether source/origin field is consistently populated. Affects attribution and pipeline gen analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-gen-forecast', 'pipeline-movement'],
    required_for_live: false,
  },
  {
    question_id: 'activity_logging_discipline',
    domain: 'data_quality',
    question: 'Do reps consistently log activities in CRM?',
    description: 'Whether calls, meetings, emails are reliably tracked. Affects activity-based metrics and hygiene detection.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['pipeline-hygiene', 'coaching'],
    required_for_live: false,
  },
  {
    question_id: 'forecast_category_discipline',
    domain: 'data_quality',
    question: 'Do reps update forecast categories consistently?',
    description: 'Whether forecast category field is maintained. Affects forecast rollup accuracy.',
    answer_type: 'boolean',
    options: [],
    depends_on: ['forecast_categories'],
    skill_dependencies: ['forecast-rollup', 'forecast-accuracy-tracking'],
    required_for_live: false,
  },
  {
    question_id: 'closed_lost_reason_required',
    domain: 'data_quality',
    question: 'Is closed lost reason a required field?',
    description: 'Whether loss reason must be provided on closed lost deals. Enables loss analysis.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['competitive-intelligence', 'deal-scoring-model'],
    required_for_live: false,
  },
  {
    question_id: 'data_governance_owner',
    domain: 'data_quality',
    question: 'Who owns CRM data quality and governance?',
    description: 'Team responsible for data cleanliness (RevOps, Sales Ops, Admin). Used for escalation.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['data-quality-audit', 'workspace-config-audit'],
    required_for_live: false,
  },
  {
    question_id: 'crm_validation_rules',
    domain: 'data_quality',
    question: 'What validation rules are enforced in CRM?',
    description: 'List of required fields and format checks. Indicates data quality discipline.',
    answer_type: 'text',
    options: [],
    depends_on: [],
    skill_dependencies: ['data-quality-audit'],
    required_for_live: false,
  },
  {
    question_id: 'duplicate_deal_detection',
    domain: 'data_quality',
    question: 'Is there a process for detecting and merging duplicate deals?',
    description: 'Whether duplicates are actively managed. Affects count-based metrics accuracy.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['data-quality-audit', 'pipeline-hygiene'],
    required_for_live: false,
  },
  {
    question_id: 'historical_data_backfill',
    domain: 'data_quality',
    question: 'Has historical data been backfilled after migrations?',
    description: 'Whether past data was successfully migrated. Affects historical trend reliability.',
    answer_type: 'boolean',
    options: [],
    depends_on: [],
    skill_dependencies: ['data-quality-audit', 'stage-velocity-benchmarks'],
    required_for_live: false,
  },
];

// ============================================================
// MASTER QUESTIONS ARRAY
// ============================================================

export const CALIBRATION_QUESTIONS: CalibrationQuestion[] = [
  ...PIPELINE_QUESTIONS,
  ...SEGMENTATION_QUESTIONS,
  ...TAXONOMY_QUESTIONS,
  ...METRICS_QUESTIONS,
  ...BUSINESS_QUESTIONS,
  ...DATA_QUALITY_QUESTIONS,
];

// ============================================================
// EXPORTS & UTILITIES
// ============================================================

/**
 * Gets all questions for a specific domain.
 */
export function getQuestionsByDomain(domain: string): CalibrationQuestion[] {
  return CALIBRATION_QUESTIONS.filter((q) => q.domain === domain);
}

/**
 * Gets a single question by ID.
 */
export function getQuestionById(questionId: string): CalibrationQuestion | null {
  return CALIBRATION_QUESTIONS.find((q) => q.question_id === questionId) ?? null;
}

/**
 * Gets all questions that block a specific skill from going LIVE.
 */
export function getSkillBlockingQuestions(skillId: string): CalibrationQuestion[] {
  return CALIBRATION_QUESTIONS.filter((q) =>
    q.skill_dependencies.includes(skillId) && q.required_for_live
  );
}

/**
 * Gets all questions marked as required_for_live.
 */
export function getRequiredQuestions(): CalibrationQuestion[] {
  return CALIBRATION_QUESTIONS.filter((q) => q.required_for_live);
}
