export const colors = {
  bg: 'var(--color-bg)',
  bgSidebar: 'var(--color-bgSidebar)',
  surface: 'var(--color-surface)',
  surfaceRaised: 'var(--color-surfaceRaised)',
  surfaceHover: 'var(--color-surfaceHover)',
  surfaceActive: 'var(--color-surfaceActive)',
  border: 'var(--color-border)',
  borderLight: 'var(--color-borderLight)',
  borderFocus: 'var(--color-borderFocus)',
  text: 'var(--color-text)',
  textSecondary: 'var(--color-textSecondary)',
  textMuted: 'var(--color-textMuted)',
  textDim: 'var(--color-textDim)',
  textTertiary: 'var(--color-textTertiary)',
  accent: 'var(--color-accent)',
  accentHover: 'var(--color-accentHover)',
  accentSoft: 'var(--color-accentSoft)',
  green: 'var(--color-green)',
  greenSoft: 'var(--color-greenSoft)',
  yellow: 'var(--color-yellow)',
  yellowSoft: 'var(--color-yellowSoft)',
  red: 'var(--color-red)',
  redSoft: 'var(--color-redSoft)',
  coral: 'var(--color-coral)',
  coralSoft: 'var(--color-coralSoft)',
  purple: 'var(--color-purple)',
  purpleSoft: 'var(--color-purpleSoft)',
  orange: 'var(--color-orange)',
  orangeSoft: 'var(--color-orangeSoft)',
} as const;

export const fonts = {
  sans: "'Outfit', -apple-system, sans-serif",
  body: "'Outfit', -apple-system, sans-serif",
  mono: "'JetBrains Mono', 'SF Mono', monospace",
} as const;
